import 'package:flutter/material.dart';

/// UI and navigation configuration per tenant business category.
class BusinessTypeConfig {
  const BusinessTypeConfig({
    required this.id,
    required this.label,
    required this.appTitle,
    required this.isFoodBusiness,
    required this.unitsSoldLabel,
    required this.primaryQuickActionLabel,
    required this.primaryQuickActionIcon,
    required this.secondaryQuickActionLabel,
    required this.secondaryQuickActionIcon,
    required this.showOrdersNav,
    required this.showInventoryNav,
    required this.showProfitNav,
    required this.showProductionDrawer,
    required this.productNoun,
    required this.emptyCatalogHint,
    required this.productIcon,
  });

  final String id;
  final String label;
  final String appTitle;
  final bool isFoodBusiness;
  final String unitsSoldLabel;
  final String primaryQuickActionLabel;
  final IconData primaryQuickActionIcon;
  final String secondaryQuickActionLabel;
  final IconData secondaryQuickActionIcon;
  final bool showOrdersNav;
  final bool showInventoryNav;
  final bool showProfitNav;
  final bool showProductionDrawer;
  final String productNoun;
  final String emptyCatalogHint;
  final IconData productIcon;

  static const fallback = BusinessTypeConfig(
    id: 'food_vendor',
    label: 'Food Vendors',
    appTitle: 'BizHub',
    isFoodBusiness: true,
    unitsSoldLabel: 'Samosas sold',
    primaryQuickActionLabel: 'Add order',
    primaryQuickActionIcon: Icons.add_shopping_cart,
    secondaryQuickActionLabel: 'Record sale',
    secondaryQuickActionIcon: Icons.payments,
    showOrdersNav: true,
    showInventoryNav: false,
    showProfitNav: true,
    showProductionDrawer: true,
    productNoun: 'samosa',
    emptyCatalogHint: 'Add products to start selling.',
    productIcon: Icons.restaurant,
  );

  static BusinessTypeConfig forType(String? typeId) {
    if (typeId == null || typeId.isEmpty) return fallback;
    return _all[typeId] ?? fallback;
  }

  static const _all = <String, BusinessTypeConfig>{
    'food_vendor': BusinessTypeConfig(
      id: 'food_vendor',
      label: 'Food Vendors',
      appTitle: 'BizHub',
      isFoodBusiness: true,
      unitsSoldLabel: 'Samosas sold',
      primaryQuickActionLabel: 'Add order',
      primaryQuickActionIcon: Icons.add_shopping_cart,
      secondaryQuickActionLabel: 'Record sale',
      secondaryQuickActionIcon: Icons.payments,
      showOrdersNav: true,
      showInventoryNav: false,
      showProfitNav: true,
      showProductionDrawer: true,
      productNoun: 'samosa',
      emptyCatalogHint: 'Prepare samosas in Production first.',
      productIcon: Icons.restaurant,
    ),
    'small_restaurant': BusinessTypeConfig(
      id: 'small_restaurant',
      label: 'Small Restaurant',
      appTitle: 'BizHub',
      isFoodBusiness: true,
      unitsSoldLabel: 'Items sold',
      primaryQuickActionLabel: 'Add order',
      primaryQuickActionIcon: Icons.restaurant_menu,
      secondaryQuickActionLabel: 'Record sale',
      secondaryQuickActionIcon: Icons.point_of_sale,
      showOrdersNav: true,
      showInventoryNav: false,
      showProfitNav: true,
      showProductionDrawer: true,
      productNoun: 'menu item',
      emptyCatalogHint: 'Add menu items in Production.',
      productIcon: Icons.restaurant_menu,
    ),
    'pharmacy': BusinessTypeConfig(
      id: 'pharmacy',
      label: 'Pharmacies',
      appTitle: 'BizHub',
      isFoodBusiness: false,
      unitsSoldLabel: 'Units sold',
      primaryQuickActionLabel: 'New sale',
      primaryQuickActionIcon: Icons.point_of_sale,
      secondaryQuickActionLabel: 'Inventory',
      secondaryQuickActionIcon: Icons.medication_outlined,
      showOrdersNav: false,
      showInventoryNav: true,
      showProfitNav: false,
      showProductionDrawer: false,
      productNoun: 'medicine',
      emptyCatalogHint: 'Add medicines in Inventory — e.g. Paracetamol, Amoxicillin.',
      productIcon: Icons.medication_outlined,
    ),
    'grocery_shop': BusinessTypeConfig(
      id: 'grocery_shop',
      label: 'Grocery Shop',
      appTitle: 'BizHub',
      isFoodBusiness: false,
      unitsSoldLabel: 'Units sold',
      primaryQuickActionLabel: 'New sale',
      primaryQuickActionIcon: Icons.point_of_sale,
      secondaryQuickActionLabel: 'Inventory',
      secondaryQuickActionIcon: Icons.storefront,
      showOrdersNav: false,
      showInventoryNav: true,
      showProfitNav: false,
      showProductionDrawer: false,
      productNoun: 'product',
      emptyCatalogHint: 'Add groceries in Inventory — e.g. Rice, Sugar, Flour.',
      productIcon: Icons.shopping_basket_outlined,
    ),
    'boutique': BusinessTypeConfig(
      id: 'boutique',
      label: 'Boutiques',
      appTitle: 'BizHub',
      isFoodBusiness: false,
      unitsSoldLabel: 'Items sold',
      primaryQuickActionLabel: 'New sale',
      primaryQuickActionIcon: Icons.point_of_sale,
      secondaryQuickActionLabel: 'Inventory',
      secondaryQuickActionIcon: Icons.checkroom_outlined,
      showOrdersNav: false,
      showInventoryNav: true,
      showProfitNav: false,
      showProductionDrawer: false,
      productNoun: 'item',
      emptyCatalogHint: 'Add clothing and accessories in Inventory.',
      productIcon: Icons.checkroom_outlined,
    ),
    'hardware_store': BusinessTypeConfig(
      id: 'hardware_store',
      label: 'Hardware Stores',
      appTitle: 'BizHub',
      isFoodBusiness: false,
      unitsSoldLabel: 'Units sold',
      primaryQuickActionLabel: 'New sale',
      primaryQuickActionIcon: Icons.point_of_sale,
      secondaryQuickActionLabel: 'Inventory',
      secondaryQuickActionIcon: Icons.hardware_outlined,
      showOrdersNav: false,
      showInventoryNav: true,
      showProfitNav: false,
      showProductionDrawer: false,
      productNoun: 'item',
      emptyCatalogHint: 'Add tools and materials in Inventory.',
      productIcon: Icons.hardware_outlined,
    ),
    'electronics_shop': BusinessTypeConfig(
      id: 'electronics_shop',
      label: 'Electronic Shop',
      appTitle: 'BizHub',
      isFoodBusiness: false,
      unitsSoldLabel: 'Units sold',
      primaryQuickActionLabel: 'New sale',
      primaryQuickActionIcon: Icons.point_of_sale,
      secondaryQuickActionLabel: 'Inventory',
      secondaryQuickActionIcon: Icons.devices_outlined,
      showOrdersNav: false,
      showInventoryNav: true,
      showProfitNav: false,
      showProductionDrawer: false,
      productNoun: 'device',
      emptyCatalogHint: 'Add phones, accessories, and electronics in Inventory.',
      productIcon: Icons.devices_outlined,
    ),
    'cybercafe': BusinessTypeConfig(
      id: 'cybercafe',
      label: 'Cybercafe',
      appTitle: 'BizHub',
      isFoodBusiness: false,
      unitsSoldLabel: 'Services sold',
      primaryQuickActionLabel: 'New sale',
      primaryQuickActionIcon: Icons.point_of_sale,
      secondaryQuickActionLabel: 'Services',
      secondaryQuickActionIcon: Icons.computer_outlined,
      showOrdersNav: false,
      showInventoryNav: true,
      showProfitNav: false,
      showProductionDrawer: false,
      productNoun: 'service',
      emptyCatalogHint: 'Add printing, internet, and computer services in Inventory.',
      productIcon: Icons.computer_outlined,
    ),
    'beauty_shop': BusinessTypeConfig(
      id: 'beauty_shop',
      label: 'Beauty & Cosmetics',
      appTitle: 'BizHub',
      isFoodBusiness: false,
      unitsSoldLabel: 'Items sold',
      primaryQuickActionLabel: 'New sale',
      primaryQuickActionIcon: Icons.point_of_sale,
      secondaryQuickActionLabel: 'Inventory',
      secondaryQuickActionIcon: Icons.spa_outlined,
      showOrdersNav: false,
      showInventoryNav: true,
      showProfitNav: false,
      showProductionDrawer: false,
      productNoun: 'product',
      emptyCatalogHint: 'Add skincare, makeup, and beauty items from the catalog.',
      productIcon: Icons.spa_outlined,
    ),
  };
}
