import 'package:flutter/material.dart';

/// UI and navigation configuration per tenant business category.
class BusinessTypeConfig {
  const BusinessTypeConfig({
    required this.id,
    required this.label,
    required this.appTitle,
    required this.isFoodBusiness,
    required this.unitsSoldLabel,
    required this.primaryQuickActionLabel,
    required this.primaryQuickActionIcon,
    required this.secondaryQuickActionLabel,
    required this.secondaryQuickActionIcon,
    required this.showOrdersNav,
    required this.showInventoryNav,
    required this.showProfitNav,
    required this.showProductionDrawer,
    required this.productNoun,
    required this.emptyCatalogHint,
    required this.globalCatalogSubtitle,
    required this.productIcon,
  });

  final String id;
  final String label;
  final String appTitle;
  final bool isFoodBusiness;
  final String unitsSoldLabel;
  final String primaryQuickActionLabel;
  final IconData primaryQuickActionIcon;
  final String secondaryQuickActionLabel;
  final IconData secondaryQuickActionIcon;
  final bool showOrdersNav;
  final bool showInventoryNav;
  final bool showProfitNav;
  final bool showProductionDrawer;
  final String productNoun;
  final String emptyCatalogHint;
  final String globalCatalogSubtitle;
  final IconData productIcon;

  static const fallback = BusinessTypeConfig(
    id: 'food_vendor',
    label: 'Food Vendors',
    appTitle: 'Akira Flow',
    isFoodBusiness: true,
    unitsSoldLabel: 'Items sold',
    primaryQuickActionLabel: 'Add order',
    primaryQuickActionIcon: Icons.add_shopping_cart,
    secondaryQuickActionLabel: 'Inventory',
    secondaryQuickActionIcon: Icons.inventory_2_outlined,
    showOrdersNav: true,
    showInventoryNav: true,
    showProfitNav: true,
    showProductionDrawer: true,
    productNoun: 'item',
    emptyCatalogHint: 'Add products in Inventory and set your selling price.',
    globalCatalogSubtitle: 'Samosa, Mandazi, Chapati, and more',
    productIcon: Icons.restaurant,
  );

  static BusinessTypeConfig forType(String? typeId) {
    if (typeId == null || typeId.isEmpty) return fallback;
    return _all[typeId] ?? fallback;
  }

  static const _all = <String, BusinessTypeConfig>{
    'food_vendor': BusinessTypeConfig(
      id: 'food_vendor',
      label: 'Food Vendors',
      appTitle: 'Akira Flow',
      isFoodBusiness: true,
      unitsSoldLabel: 'Items sold',
      primaryQuickActionLabel: 'Add order',
      primaryQuickActionIcon: Icons.add_shopping_cart,
      secondaryQuickActionLabel: 'Inventory',
      secondaryQuickActionIcon: Icons.inventory_2_outlined,
      showOrdersNav: true,
      showInventoryNav: true,
      showProfitNav: true,
      showProductionDrawer: true,
      productNoun: 'item',
      emptyCatalogHint: 'Add snacks and meals in Inventory and set your price.',
      globalCatalogSubtitle: 'Samosa, Mandazi, Chapati, Ugali, and more',
      productIcon: Icons.restaurant,
    ),
    'small_restaurant': BusinessTypeConfig(
      id: 'small_restaurant',
      label: 'Small Restaurant',
      appTitle: 'Akira Flow',
      isFoodBusiness: true,
      unitsSoldLabel: 'Items sold',
      primaryQuickActionLabel: 'Add order',
      primaryQuickActionIcon: Icons.restaurant_menu,
      secondaryQuickActionLabel: 'Inventory',
      secondaryQuickActionIcon: Icons.inventory_2_outlined,
      showOrdersNav: true,
      showInventoryNav: true,
      showProfitNav: true,
      showProductionDrawer: true,
      productNoun: 'menu item',
      emptyCatalogHint: 'Add menu items in Inventory and set your selling price.',
      globalCatalogSubtitle: 'Ugali, Rice, Chicken, Soda, and more',
      productIcon: Icons.restaurant_menu,
    ),
    'pharmacy': BusinessTypeConfig(
      id: 'pharmacy',
      label: 'Pharmacies',
      appTitle: 'Akira Flow',
      isFoodBusiness: false,
      unitsSoldLabel: 'Units sold',
      primaryQuickActionLabel: 'New sale',
      primaryQuickActionIcon: Icons.point_of_sale,
      secondaryQuickActionLabel: 'Inventory',
      secondaryQuickActionIcon: Icons.medication_outlined,
      showOrdersNav: false,
      showInventoryNav: true,
      showProfitNav: true,
      showProductionDrawer: false,
      productNoun: 'medicine',
      emptyCatalogHint: 'Add medicines in Inventory — e.g. Paracetamol, Amoxicillin.',
      globalCatalogSubtitle: 'Paracetamol, Amoxicillin, Cough syrup, and more',
      productIcon: Icons.medication_outlined,
    ),
    'grocery_shop': BusinessTypeConfig(
      id: 'grocery_shop',
      label: 'General Retail Kiosk',
      appTitle: 'Akira Flow',
      isFoodBusiness: false,
      unitsSoldLabel: 'Units sold',
      primaryQuickActionLabel: 'New sale',
      primaryQuickActionIcon: Icons.point_of_sale,
      secondaryQuickActionLabel: 'Inventory',
      secondaryQuickActionIcon: Icons.storefront,
      showOrdersNav: false,
      showInventoryNav: true,
      showProfitNav: true,
      showProductionDrawer: false,
      productNoun: 'product',
      emptyCatalogHint: 'Add unga, oil, soap, sugar, and other kiosk staples.',
      globalCatalogSubtitle: 'Unga, cooking oil, bar soap, sugar, and more',
      productIcon: Icons.shopping_basket_outlined,
    ),
    'mama_mboga': BusinessTypeConfig(
      id: 'mama_mboga',
      label: 'Fresh Foods (Mama Mboga)',
      appTitle: 'Akira Flow',
      isFoodBusiness: false,
      unitsSoldLabel: 'Items sold',
      primaryQuickActionLabel: 'New sale',
      primaryQuickActionIcon: Icons.point_of_sale,
      secondaryQuickActionLabel: 'Inventory',
      secondaryQuickActionIcon: Icons.eco_outlined,
      showOrdersNav: false,
      showInventoryNav: true,
      showProfitNav: true,
      showProductionDrawer: false,
      productNoun: 'item',
      emptyCatalogHint: 'Add sukuma, tomatoes, onions, potatoes, and other produce.',
      globalCatalogSubtitle: 'Sukuma wiki, tomatoes, hoho, bananas, and more',
      productIcon: Icons.eco_outlined,
    ),
    'dairy_shop': BusinessTypeConfig(
      id: 'dairy_shop',
      label: 'Milk Bar / Dairy',
      appTitle: 'Akira Flow',
      isFoodBusiness: false,
      unitsSoldLabel: 'Litres sold',
      primaryQuickActionLabel: 'New sale',
      primaryQuickActionIcon: Icons.point_of_sale,
      secondaryQuickActionLabel: 'Inventory',
      secondaryQuickActionIcon: Icons.water_drop_outlined,
      showOrdersNav: false,
      showInventoryNav: true,
      showProfitNav: true,
      showProductionDrawer: false,
      productNoun: 'item',
      emptyCatalogHint: 'Add milk, mala, yogurt, cheese, and butter.',
      globalCatalogSubtitle: 'Raw milk, packets, mala, yogurt, and more',
      productIcon: Icons.water_drop_outlined,
    ),
    'poultry_shop': BusinessTypeConfig(
      id: 'poultry_shop',
      label: 'Poultry & Egg Supply',
      appTitle: 'Akira Flow',
      isFoodBusiness: false,
      unitsSoldLabel: 'Units sold',
      primaryQuickActionLabel: 'New sale',
      primaryQuickActionIcon: Icons.point_of_sale,
      secondaryQuickActionLabel: 'Inventory',
      secondaryQuickActionIcon: Icons.set_meal_outlined,
      showOrdersNav: false,
      showInventoryNav: true,
      showProfitNav: true,
      showProductionDrawer: false,
      productNoun: 'item',
      emptyCatalogHint: 'Add egg trays, live birds, broilers, and chick mash.',
      globalCatalogSubtitle: 'Egg trays, kienyeji eggs, broilers, and more',
      productIcon: Icons.set_meal_outlined,
    ),
    'wholesale': BusinessTypeConfig(
      id: 'wholesale',
      label: 'Wholesale Store',
      appTitle: 'Akira Flow',
      isFoodBusiness: false,
      unitsSoldLabel: 'Units sold',
      primaryQuickActionLabel: 'New sale',
      primaryQuickActionIcon: Icons.point_of_sale,
      secondaryQuickActionLabel: 'Inventory',
      secondaryQuickActionIcon: Icons.inventory_2_outlined,
      showOrdersNav: false,
      showInventoryNav: true,
      showProfitNav: true,
      showProductionDrawer: false,
      productNoun: 'pack',
      emptyCatalogHint: 'Add bales, cartons, crates, and sacks.',
      globalCatalogSubtitle: 'Unga bales, soap cartons, soda crates, and more',
      productIcon: Icons.inventory_2_outlined,
    ),
    'liquor_store': BusinessTypeConfig(
      id: 'liquor_store',
      label: 'Wines & Spirits',
      appTitle: 'Akira Flow',
      isFoodBusiness: false,
      unitsSoldLabel: 'Bottles sold',
      primaryQuickActionLabel: 'New sale',
      primaryQuickActionIcon: Icons.point_of_sale,
      secondaryQuickActionLabel: 'Inventory',
      secondaryQuickActionIcon: Icons.local_bar_outlined,
      showOrdersNav: false,
      showInventoryNav: true,
      showProfitNav: true,
      showProductionDrawer: false,
      productNoun: 'bottle',
      emptyCatalogHint: 'Add beers, gin, vodka, wines, ciders, and mixers.',
      globalCatalogSubtitle: 'Tusker, White Cap, gin, wine, and more',
      productIcon: Icons.local_bar_outlined,
    ),
    'gas_water': BusinessTypeConfig(
      id: 'gas_water',
      label: 'Gas & Water Refill',
      appTitle: 'Akira Flow',
      isFoodBusiness: false,
      unitsSoldLabel: 'Refills sold',
      primaryQuickActionLabel: 'New sale',
      primaryQuickActionIcon: Icons.point_of_sale,
      secondaryQuickActionLabel: 'Inventory',
      secondaryQuickActionIcon: Icons.local_gas_station_outlined,
      showOrdersNav: false,
      showInventoryNav: true,
      showProfitNav: true,
      showProductionDrawer: false,
      productNoun: 'refill',
      emptyCatalogHint: 'Add 6kg/13kg gas, cylinders, and water jerry cans.',
      globalCatalogSubtitle: '6kg gas, 13kg gas, 20L water, and more',
      productIcon: Icons.local_gas_station_outlined,
    ),
    'boutique': BusinessTypeConfig(
      id: 'boutique',
      label: 'Clothing Boutique',
      appTitle: 'Akira Flow',
      isFoodBusiness: false,
      unitsSoldLabel: 'Items sold',
      primaryQuickActionLabel: 'New sale',
      primaryQuickActionIcon: Icons.point_of_sale,
      secondaryQuickActionLabel: 'Inventory',
      secondaryQuickActionIcon: Icons.checkroom_outlined,
      showOrdersNav: false,
      showInventoryNav: true,
      showProfitNav: true,
      showProductionDrawer: false,
      productNoun: 'item',
      emptyCatalogHint: 'Add t-shirts, dresses, jeans, kidswear, and belts.',
      globalCatalogSubtitle: "Men's t-shirts, dresses, jeans, rompers, and more",
      productIcon: Icons.checkroom_outlined,
    ),
    'shoe_store': BusinessTypeConfig(
      id: 'shoe_store',
      label: 'Shoe Store',
      appTitle: 'Akira Flow',
      isFoodBusiness: false,
      unitsSoldLabel: 'Pairs sold',
      primaryQuickActionLabel: 'New sale',
      primaryQuickActionIcon: Icons.point_of_sale,
      secondaryQuickActionLabel: 'Inventory',
      secondaryQuickActionIcon: Icons.shopping_bag_outlined,
      showOrdersNav: false,
      showInventoryNav: true,
      showProfitNav: true,
      showProductionDrawer: false,
      productNoun: 'pair',
      emptyCatalogHint: 'Add school shoes, sneakers, leather shoes, and polish.',
      globalCatalogSubtitle: 'School shoes, sneakers, sandals, heels, and more',
      productIcon: Icons.shopping_bag_outlined,
    ),
    'hardware_store': BusinessTypeConfig(
      id: 'hardware_store',
      label: 'Hardware Store',
      appTitle: 'Akira Flow',
      isFoodBusiness: false,
      unitsSoldLabel: 'Units sold',
      primaryQuickActionLabel: 'New sale',
      primaryQuickActionIcon: Icons.point_of_sale,
      secondaryQuickActionLabel: 'Inventory',
      secondaryQuickActionIcon: Icons.hardware_outlined,
      showOrdersNav: false,
      showInventoryNav: true,
      showProfitNav: true,
      showProductionDrawer: false,
      productNoun: 'item',
      emptyCatalogHint: 'Add cement, nails, iron sheets, paint, pipes, and locks.',
      globalCatalogSubtitle: 'Cement, nails, iron sheets, paint, and more',
      productIcon: Icons.hardware_outlined,
    ),
    'agrovet': BusinessTypeConfig(
      id: 'agrovet',
      label: 'Agrovets',
      appTitle: 'Akira Flow',
      isFoodBusiness: false,
      unitsSoldLabel: 'Units sold',
      primaryQuickActionLabel: 'New sale',
      primaryQuickActionIcon: Icons.point_of_sale,
      secondaryQuickActionLabel: 'Inventory',
      secondaryQuickActionIcon: Icons.grass_outlined,
      showOrdersNav: false,
      showInventoryNav: true,
      showProfitNav: true,
      showProductionDrawer: false,
      productNoun: 'item',
      emptyCatalogHint: 'Add fertilizer, maize seed, dewormers, and sprayers.',
      globalCatalogSubtitle: 'DAP, CAN, maize seed, dewormers, and more',
      productIcon: Icons.grass_outlined,
    ),
    'electronics_shop': BusinessTypeConfig(
      id: 'electronics_shop',
      label: 'Electronic Shop',
      appTitle: 'Akira Flow',
      isFoodBusiness: false,
      unitsSoldLabel: 'Units sold',
      primaryQuickActionLabel: 'New sale',
      primaryQuickActionIcon: Icons.point_of_sale,
      secondaryQuickActionLabel: 'Inventory',
      secondaryQuickActionIcon: Icons.devices_outlined,
      showOrdersNav: false,
      showInventoryNav: true,
      showProfitNav: true,
      showProductionDrawer: false,
      productNoun: 'device',
      emptyCatalogHint: 'Add phones, accessories, and electronics in Inventory.',
      globalCatalogSubtitle: 'Phone charger, Earphones, USB cable, and more',
      productIcon: Icons.devices_outlined,
    ),
    'cybercafe': BusinessTypeConfig(
      id: 'cybercafe',
      label: 'Cyber Cafe',
      appTitle: 'Akira Flow',
      isFoodBusiness: false,
      unitsSoldLabel: 'Services sold',
      primaryQuickActionLabel: 'New sale',
      primaryQuickActionIcon: Icons.point_of_sale,
      secondaryQuickActionLabel: 'Services',
      secondaryQuickActionIcon: Icons.computer_outlined,
      showOrdersNav: false,
      showInventoryNav: true,
      showProfitNav: true,
      showProductionDrawer: false,
      productNoun: 'service',
      emptyCatalogHint: 'Add printing, photocopy, laminating, and flash disks.',
      globalCatalogSubtitle: 'A4 printing, photocopy, laminating, and more',
      productIcon: Icons.computer_outlined,
    ),
    'salon': BusinessTypeConfig(
      id: 'salon',
      label: 'Salon / Kinyozi',
      appTitle: 'Akira Flow',
      isFoodBusiness: false,
      unitsSoldLabel: 'Services sold',
      primaryQuickActionLabel: 'New sale',
      primaryQuickActionIcon: Icons.point_of_sale,
      secondaryQuickActionLabel: 'Services',
      secondaryQuickActionIcon: Icons.content_cut,
      showOrdersNav: false,
      showInventoryNav: true,
      showProfitNav: true,
      showProductionDrawer: false,
      productNoun: 'service',
      emptyCatalogHint: 'Add haircuts, braiding, washing, facials, and barber products.',
      globalCatalogSubtitle: 'Haircut, braiding, facial, aftershave, and more',
      productIcon: Icons.content_cut,
    ),
    'beauty_shop': BusinessTypeConfig(
      id: 'beauty_shop',
      label: 'Cosmetics Shop',
      appTitle: 'Akira Flow',
      isFoodBusiness: false,
      unitsSoldLabel: 'Items sold',
      primaryQuickActionLabel: 'New sale',
      primaryQuickActionIcon: Icons.point_of_sale,
      secondaryQuickActionLabel: 'Inventory',
      secondaryQuickActionIcon: Icons.spa_outlined,
      showOrdersNav: false,
      showInventoryNav: true,
      showProfitNav: true,
      showProductionDrawer: false,
      productNoun: 'product',
      emptyCatalogHint: 'Add braids, lotions, wigs, makeup, and hair oil.',
      globalCatalogSubtitle: 'Braids, lotions, wigs, lipstick, perfume, and more',
      productIcon: Icons.spa_outlined,
    ),
    'butchery': BusinessTypeConfig(
      id: 'butchery',
      label: 'Butchery',
      appTitle: 'Akira Flow',
      isFoodBusiness: false,
      unitsSoldLabel: 'Kilos sold',
      primaryQuickActionLabel: 'New sale',
      primaryQuickActionIcon: Icons.point_of_sale,
      secondaryQuickActionLabel: 'Inventory',
      secondaryQuickActionIcon: Icons.set_meal_outlined,
      showOrdersNav: false,
      showInventoryNav: true,
      showProfitNav: true,
      showProductionDrawer: false,
      productNoun: 'cut',
      emptyCatalogHint: 'Add beef, goat, pork, chicken, matumbo, and sausages.',
      globalCatalogSubtitle: 'Beef, mbuzi, pork chops, chicken, smokies, and more',
      productIcon: Icons.set_meal_outlined,
    ),
  };
}
